### ISSUE TITLE
License

### ISSUE THREAD

**Issue by seasick** [seasick/openscad-web-gui#11]
Figure out which license to pick

**Comment by remram44** [comment]
You might not have too much of a choice here. [Openscad is GPL](https://github.com/openscad/openscad/blob/master/COPYING), it will be difficult from a legal standpoint to use anything else.

> You must cause any work that you distribute or publish, that in whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License.

**Comment by seasick** [comment]
Currently, the used dependencies use one of the following licences

* "Apache-2.0"
* "BSD-3-Clause"
* "MIT"

Those seem to be generally compatible with GPL - so GPL it is.

**Comment by remram44** [comment]
You probably want version 3

https://www.gnu.org/licenses/license-list.html#apache2

**Comment by seasick** [comment]
Thanks for pointing that out.

I was shortly worried that GPL2 & 3 are incompatible, but luckily the license contains this section:

> If the Program specifies a version number of this License which applies to it and "any later version", you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation.
