### ISSUE TITLE
//!OpenSCAD is included and overwrites first variable name

### ISSUE THREAD

**Issue by WillAdams** [seasick/openscad-web-gui#21]
Given a file such as:

https://github.com/WillAdams/Design_Into_3D/blob/master/openscadwebgui/Impossible_Dovetail_Box.scad

which begins with:

    //!OpenSCAD
    
    Height = 1.5;
    Width_and_Depth = 3;

The label for "Height" is overwritten by "!OpenSCAD":

![image](https://github.com/seasick/openscad-web-gui/assets/3543154/10b2bf1f-8368-4de9-ac33-3fd94f3b3840)

as shown at the link:

https://seasick.github.io/openscad-web-gui/?https://raw.githubusercontent.com/WillAdams/Design_Into_3D/master/openscadwebgui/Impossible_Dovetail_Box.scad

**Comment by seasick** [comment]
Thanks for reporting the issue - a fix has been deployed

**Comment by seasick** [comment]
Thanks for reporting the issue - a fix has been deployed
