### ISSUE TITLE
Consider adding GitHub topics

### ISSUE THREAD

**Issue by remram44** [seasick/openscad-web-gui#34]
**Is your feature request related to a problem? Please describe.**
Many openscad-related tools are tagged "openscad" so [they can be listed easily](https://github.com/topics/openscad). You might want to add the `openscad` topic to this repo too.

**Additional context**
It wasn't very easy to find this repo, and it is exactly what I wanted. Thank you so much for making it! I first found [openscad-playground](https://github.com/openscad/openscad-playground) but it has no customizer yet.

**Comment by seasick** [comment]
Although I'm quite busy atm, this was something I could do quite easily :) 
Thanks for the suggestion
