### ISSUE TITLE
Edge Browser on Windows 11 has call stack error

### ISSUE THREAD

**Issue by WillAdams** [seasick/openscad-web-gui#9]
Loading the link/file:

https://seasick.github.io/openscad-web-gui/?https://raw.githubusercontent.com/WillAdams/Design_Into_3D/master/designinto3dboxfitted.scad

on the Edge browser in Windows 11

results in an

>Uncaught Error: OpenSCAD exited with an error: Maximum call stack size exceeded

error:

<img width="460" alt="image" src="https://github.com/seasick/openscad-web-gui/assets/3543154/6c289231-d811-467e-a4a5-c64d726e4467">

EDIT: Note that it works in the Edge browser in Windows 10 (also Firefox, also Safari on the current MacOS)

**Comment by seasick** [comment]
Just fyi: It may take some time until this is fixed, as I don't have immediate access to a Win11 machine.

**Comment by seasick** [comment]
I was able to test this on Win11 with Edge today, but unfortunately, I couldn't reproduce the issue.

@WillAdams does the error happen, when you open the page or does it only happen on a specific action (e.g. exporting to AMF)? Do you change any of the parameters in the customizer?

**Comment by WillAdams** [comment]
It happens on open --- hopefully it will go away at the next update --- if it doesn't, I'll let you know all the specifics and re-open this, or make a new issue.
